name: Publish

on:
  push:
    branches:
      - 'release/**'

env:
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPEUSERNAME }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPEPASSWORD }}
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Extract branch name
        run: |
          branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          branch=${branch:8}
          echo "value=$branch" >> $GITHUB_OUTPUT
          echo "library_version=$branch" >> $GITHUB_ENV
        id: version
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish YandexMapKitKMP
        run: ./gradlew :yandex-mapkit-kmp:publishAndReleaseToMavenCentral --no-configuration-cache
      - name: Publish YandexMapKitKMPCompose
        run: ./gradlew :yandex-mapkit-kmp-compose:publishAndReleaseToMavenCentral --no-configuration-cache
      - name: Publish YandexMapKitKMPMOKO
        run: ./gradlew :yandex-mapkit-kmp-moko:publishAndReleaseToMavenCentral --no-configuration-cache
      - name: Publish YandexMapKitKMPMOKOCompose
        run: ./gradlew :yandex-mapkit-kmp-moko-compose:publishAndReleaseToMavenCentral --no-configuration-cache